# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KoGRRdCyBqE-W3qyBNFTcNcJ2BnrZlo0
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# --- KONFIGURASI HALAMAN ---
st.set_page_config(page_title="FraudGuard ML", layout="wide")

# --- LOAD ASSETS ---
@st.cache_resource
def load_assets():
    model = joblib.load('model_rf_smote.pkl')
    scaler = joblib.load('scaler_amount.pkl')
    return model, scaler

try:
    model, scaler = load_assets()
except:
    st.error("Model atau Scaler tidak ditemukan! Pastikan file .pkl ada di direktori yang sama.")
    st.stop()

# --- SIDEBAR ---
st.sidebar.title("🛡️ FraudGuard AI")
st.sidebar.info("Sistem Deteksi Penipuan Kartu Kredit Berbasis Machine Learning.")
mode = st.sidebar.radio("Pilih Mode:", [ "Bulk Detection"])

# --- FUNGSI UTAMA ---
def get_risk_score(prob):
    score = prob * 100
    if score < 30:
        return score, "SAFE", "green"
    elif score < 70:
        return score, "SUSPICIOUS", "orange"
    else:
        return score, "FRAUD LIKELY", "red"

# --- MODE 1: SINGLE PREDICTION ---
if mode == "Single Prediction":
    st.title("🔍 Single Transaction Checker")
    st.write("Masukkan detail transaksi di bawah ini untuk mendapatkan analisis risiko.")

    col1, col2 = st.columns(2)
    with col1:
        amount = st.number_input("Transaction Amount (Euro)", min_value=0.0, value=100.0)
        time = st.number_input("Seconds since first transaction (Time)", min_value=0.0, value=0.0)

    with col2:
        st.write("**PCA Features (V1-V28)**")
        v_features = [st.number_input(f"V{i}", value=0.0) for i in range(1, 29)]

    if st.button("Analyze Risk"):
        # Preprocessing
        amt_scaled = scaler.transform([[amount]])[0][0]
        # Catatan: Di notebook asli, Time juga di-scale. Kita asumsikan scaler yang sama atau default.
        # Untuk demo ini kita masukkan input ke format model (30 kolom)
        features = v_features + [amt_scaled, time]

        prob = model.predict_proba([features])[0][1]
        score, label, color = get_risk_score(prob)

        st.markdown("--- ")
        st.subheader("Analysis Result:")
        st.metric("Risk Score", f"{score:.1f}/100", delta=label, delta_color="inverse" if label != "SAFE" else "normal")

        if label == "SAFE":
            st.success(f"STATUS: {label} - Transaksi ini dinilai aman.")
        elif label == "SUSPICIOUS":
            st.warning(f"STATUS: {label} - Perlu verifikasi tambahan (MFA) atau review manual.")
        else:
            st.error(f"STATUS: {label} - Transaksi sangat mencurigakan. Segera blokir!")

# --- MODE 2: BULK DETECTION ---
else:
    st.title("📊 Bulk Transaction Detection")
    st.write("Unggah file CSV berisi data transaksi untuk deteksi massal.")

    uploaded_file = st.file_uploader("Choose a CSV file", type="csv")

    if uploaded_file:
        data = pd.read_csv(uploaded_file)
        if st.checkbox("Show raw data"):
            st.write(data.head())

        if st.button("Run Batch Analysis"):
            # Asumsi kolom sudah sesuai dengan requirement model
            # (Urutan: V1-V28, Amount_scaled, Time_scaled)
            # Catatan: User perlu memastikan kolom sudah ter-scale di file input atau script ini melakukan scaling

            probs = model.predict_proba(data)[:, 1]
            data['Risk_Score'] = (probs * 100).round(1)
            data['Status'] = data['Risk_Score'].apply(lambda x: get_risk_score(x/100)[1])

            # Tampilkan Top 10 Paling Mencurigakan
            suspicious = data.sort_values(by='Risk_Score', ascending=False).head(10)

            st.subheader("🚨 Top 10 Most Suspicious Transactions")
            st.table(suspicious[['Risk_Score', 'Status'] + [col for col in data.columns if col not in ['Risk_Score', 'Status']]].iloc[:, :5])

            st.download_button("Download Analysis Results", data.to_csv(index=False), "fraud_analysis_results.csv", "text/csv")